name: torrent_app
description: A P2P torrent streaming app with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # HTTP Client
  dio: ^5.4.0
  retrofit: ^4.0.3

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON Serialization
  json_annotation: ^4.8.1

  # P2P & Torrent
  # Note: These would need to be implemented/custom built
  webtorrent: ^0.3.0

  # Video Player
  video_player: ^2.8.2
  chewie: ^1.7.4

  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296

  # Navigation
  go_router: ^12.1.3

  # Utilities
  intl: ^0.18.1
  logger: ^2.0.2+1
  permission_handler: ^11.1.0

  # FFI for native libraries
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/